- name: delete interface xe-0/0/3 and xe-0/0/4
  junos_config:
    lines:
      - delete interfaces xe-0/0/3 unit 0
      - delete interfaces xe-0/0/4 unit 0

- name: vlan set
  junos_config:
    lines:
      - set vlans vlan10 vlan-id 10

- name: lag description
  junos_config:
    lines:
      - set interfaces xe-0/0/3 description ae10
      - set interfaces xe-0/0/4 description ae10

- name: ae10 seting
  junos_config:
    lines:
      - set interfaces ae10 description ae10
      - set interfaces xe-0/0/3 ether-options 802.3ad ae10
      - set interfaces xe-0/0/4 ether-options 802.3ad ae10
      - set interfaces ae0 unit 0 family ethernet-switching
      - set chassis aggregated-devices ethernet device-count 5
      - set interfaces ae10 aggregated-ether-options lacp active
      - set interfaces ae10 aggregated-ether-options lacp periodic fast
      - set interfaces ae0 unit 0 family ethernet-switching port-mode access
      - set interfaces ae0 unit 0 family ethernet-switching vlan members V10

# - name: Create interface using aggregate ae10
#   junos_interface:
#     aggregate:
#       - name: xe-0/0/3
#         description: "ae10_{{ae10_opposing_device}}_xe-0/0/3"
#       - name: xe-0/0/4
#         description: "ae10_{{ae10_opposing_device}}_xe-0/0/4"

# - name: configure link aggregation ae10
#   junos_linkagg:
#     name: ae10
#     members:
#       - xe-0/0/3
#       - xe-0/0/4
#     device_count: 5
#     state: present
#     active: True
# #    lacp: active
# # lacpはversion2.4ではパラメータがおかしいと言われて動かない可能性がある
